apiVersion: v1
kind: Service
metadata:
  name: realfood-shipping-service
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
  selector:
    app: realfood-shipping-app