apiVersion: apps/v1
kind: Deployment
metadata:
  name: realfood-shipping-app
spec:
  selector:
    matchLabels:
      app: realfood-shipping-app
  replicas: 1
  template:
    metadata:
      labels:
        app: realfood-shipping-app
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: "realfood-shipping-postgres"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "root"
            - name: RABBITMQ_HOST
              value: "realfood-rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: JWT_SECRET
              value: "a2ffb28f-23ec-4939-b2b3-c966de6a751d"
            - name: SHIPMENTS_BATCH_RATE
              value: "0 * * * * *"
          image: cloudappsteam/es.urjc.realfood.shipping:1.3.0
          imagePullPolicy: IfNotPresent
          name: realfood-shipping-app
          ports:
            - containerPort: 8080
      restartPolicy: Always