apiVersion: v1
kind: Service
metadata:
  labels:
    app: realfood-shipping-postgres
  name: realfood-shipping-postgres
spec:
  type: ClusterIP
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: realfood-shipping-postgres